apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
    version: "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: api
          image: gmoxfr/vgr:api-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: api-secrets
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 81
      targetPort: 8000
  type: LoadBalancer
status:
  loadBalancer: {}

---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: vgr-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"

---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vgr-routing
spec:
  hosts:
  - "*"
  gateways:
  - vgr-gateway
  http:
  - match:
    - uri:
        prefix: /api
    route:
    - destination:
        host: api.default.svc.cluster.local
        port:
          number: 81
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: web.default.svc.cluster.local
        port:
          number: 80