name: Build and Push Multiple Docker Images

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build-and-push:
        name: Build and Push Docker Images
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v2

            # 🔥 Build et push l'image API
            - name: Build and Push API Docker Image
              uses: docker/build-push-action@v4
              with:
                context: ./api  # Contexte du backend API
                file: ./docker/api.Dockerfile
                push: true
                platforms: linux/amd64,linux/arm64
                tags: ${{ secrets.DOCKER_USERNAME }}/vgr:api-latest