name: Build and Push Multiple Docker Images

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    api-build-and-push:
        name: Build and Push API Docker Image
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v2

            # 🔥 Build et push l'image API
            - name: Build and Push API Docker Image
              uses: docker/build-push-action@v4
              with:
                context: ./api  # Contexte du backend API
                file: ./docker/api.Dockerfile
                push: true
                platforms: linux/amd64,linux/arm64
                tags: ${{ secrets.DOCKER_USERNAME }}/vgr:api-latest

    web-build-and-push:
        name: Build and Push WEB Docker Image
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v2

            # 🔥 Build et push l'image API
            - name: Build and Push API Docker Image
              uses: docker/build-push-action@v4
              with:
                context: ./web  # Contexte du backend API
                file: ./docker/web.Dockerfile
                push: true
                platforms: linux/amd64,linux/arm64
                tags: ${{ secrets.DOCKER_USERNAME }}/vgr:web-latest

    images-build-and-push:
        name: Build and Push IMAGES API Docker Image
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v2

            # 🔥 Build et push l'image API
            - name: Build and Push API Docker Image
              uses: docker/build-push-action@v4
              with:
                context: ./services/images  # Contexte du backend API
                file: ./docker/images.Dockerfile
                push: true
                platforms: linux/amd64,linux/arm64
                tags: ${{ secrets.DOCKER_USERNAME }}/vgr:images-latest

    graph-build-and-push:
        name: Build and Push GRAPH API Docker Image
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v2

            # 🔥 Build et push l'image API
            - name: Build and Push API Docker Image
              uses: docker/build-push-action@v4
              with:
                context: ./services/graph_stats  # Contexte du backend API
                file: ./docker/graph_stats.Dockerfile
                push: true
                platforms: linux/amd64,linux/arm64
                tags: ${{ secrets.DOCKER_USERNAME }}/vgr:graph-latest

    export-build-and-push:
        name: Build and Push EXPORT Docker Image
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Build and Push API Docker Image
              uses: docker/build-push-action@v4
              with:
                context: ./services/export  # Contexte du backend API
                file: ./docker/export.Dockerfile
                push: true
                platforms: linux/amd64,linux/arm64
                tags: ${{ secrets.DOCKER_USERNAME }}/vgr:export-latest

    import-build-and-push:
        name: Build and Push IMPORT Docker Image
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Login to DockerHub
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Build and Push API Docker Image
              uses: docker/build-push-action@v4
              with:
                context: ./services/import  # Contexte du backend API
                file: ./docker/import.Dockerfile
                push: true
                platforms: linux/amd64,linux/arm64
                tags: ${{ secrets.DOCKER_USERNAME }}/vgr:import-latest